### ISSUE TITLE
Deal with abbreviations

### ISSUE THREAD

**Issue by jadebuckwalter** [jadebuckwalter/course-connect#25]
Include common abbreviations ("APUSH" for "AP United States History", for example) so that the correct search results are displayed.

**Comment by psvenk** [comment]
It may be good to make searches with abbreviations trigger multiple queries. For example, a search that contains "cs" can output the union of the search results with "cs" and the search results with "computer science". This would also enable bidirectional abbreviation relations to mark two things as synonyms. For example, "wellness" could be an abbreviation for "health" and vice versa, so that searching for either one yields all health/wellness courses.
